# Generated by Django 5.2.13 on 2026-04-11 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("serenova", "0005_comment_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reaction",
            unique_together={("user", "post")},
        ),
        migrations.AddField(
            model_name="reaction",
            name="reaction_type",
            field=models.CharField(
                choices=[
                    ("support", "❤️ Support"),
                    ("relate", "🤝 Relate"),
                    ("calm", "🌿 Calm"),
                    ("strength", "💪 Strength"),
                    ("appreciate", "🌟 Appreciate"),
                ],
                default="support",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="reaction",
            name="type",
        ),
    ]
