# Generated by Django 5.2.13 on 2026-04-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("serenova", "0008_journalentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="mood",
            field=models.CharField(
                choices=[
                    ("happy", "Happy"),
                    ("sad", "Sad"),
                    ("anxious", "Anxious"),
                    ("motivated", "Motivated"),
                    ("calm", "Calm"),
                ],
                default="calm",
                max_length=20,
            ),
        ),
    ]
