# Generated by Django 5.2.13 on 2026-04-15 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("serenova", "0009_post_mood"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="serenova.post",
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="serenova.post",
            ),
        ),
    ]
