# Generated by Django 5.2.13 on 2026-04-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("serenova", "0010_alter_comment_post_alter_reaction_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
