# Generated by Django 5.2.13 on 2026-04-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("serenova", "0011_alter_comment_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=models.CharField(
                choices=[
                    ("IN", "India"),
                    ("US", "United States"),
                    ("UK", "United Kingdom"),
                    ("CA", "Canada"),
                    ("AU", "Australia"),
                    ("DE", "Germany"),
                    ("FR", "France"),
                    ("JP", "Japan"),
                    ("CN", "China"),
                    ("BR", "Brazil"),
                    ("IT", "Italy"),
                    ("ES", "Spain"),
                    ("NL", "Netherlands"),
                    ("BE", "Belgium"),
                    ("SG", "Singapore"),
                    ("ZA", "South Africa"),
                    ("RU", "Russia"),
                    ("MX", "Mexico"),
                    ("KR", "South Korea"),
                    ("AE", "UAE"),
                ],
                max_length=100,
            ),
        ),
    ]
